# Examples

## Wiki Chinese Sample 

### Char Level

In [1]:
from nlptext.base import BasicObject

########### Wiki ###########
CORPUSPath = 'corpus/wiki_cn_sample/'

Corpus2GroupMethod = '.txt'

Group2TextMethod   = 'line'

Text2SentMethod  = 'whole'

Sent2TokenMethod = 'iter'
TOKENLevel = 'char'
min_token_freq = 1

use_hyper = ['pos']

anno = False
anno_keywords = {}


BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache


'File'
corpus/wiki_cn_sample/sample_wiki_smp.txt


Loading model cost 0.611 seconds.
Prefix dict has been built succesfully.


Total Num of All    Tokens 13878
Total Num of Unique Tokens 1087
CORPUS	it is Dumped into file: data/wiki_cn_sample/char/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
GROUP	it is Dumped into file: data/wiki_cn_sample/char/Pyramid/GROUP.p
GROUP	the length of it is   : 1
TEXT	it is Dumped into file: data/wiki_cn_sample/char/Pyramid/TEXT.p
TEXT	the length of it is   : 100
SENT	it is Dumped into file: data/wiki_cn_sample/char/Pyramid/SENT.p
SENT	the length of it is   : 100
TOKEN	it is Dumped into file: data/wiki_cn_sample/char/Pyramid/TOKEN.p
TOKEN	the length of it is   : 13878
**************************************** 

pos-bioes	is Dumped into file: data/wiki_cn_sample/char/Vocab/pos-bioes.voc
pos-bioes	the length of it is   : 229
		Write to: data/wiki_cn_sample/char/Vocab/pos-bioes.tsv
token   	is Dumped into file: data/wiki_cn_sample/char/Vocab/token.voc
token   	the length of it is   : 1087
		Write to: data/wiki_cn_sample/char/Vocab/token.tsv
***************************************

### Word Level

In [1]:
from nlptext.base import BasicObject

########### Wiki ###########
CORPUSPath = 'corpus/wiki_cn_sample/'

Corpus2GroupMethod = '.txt'

Group2TextMethod   = 'line'

Text2SentMethod  = 'whole'

Sent2TokenMethod = 'pos'
TOKENLevel = 'word'
min_token_freq = 1

use_hyper = {'pos'}


anno = False
anno_keywords = {}


BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


Building prefix dict from the default dictionary ...


'File'
corpus/wiki_cn_sample/sample_wiki_smp.txt


Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.996 seconds.
Prefix dict has been built succesfully.


Total Num of All    Tokens 8407
Total Num of Unique Tokens 2000
CORPUS	it is Dumped into file: data/wiki_cn_sample/word/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
GROUP	it is Dumped into file: data/wiki_cn_sample/word/Pyramid/GROUP.p
GROUP	the length of it is   : 1
TEXT	it is Dumped into file: data/wiki_cn_sample/word/Pyramid/TEXT.p
TEXT	the length of it is   : 100
SENT	it is Dumped into file: data/wiki_cn_sample/word/Pyramid/SENT.p
SENT	the length of it is   : 100
TOKEN	it is Dumped into file: data/wiki_cn_sample/word/Pyramid/TOKEN.p
TOKEN	the length of it is   : 8407
**************************************** 

pos-bioes	is Dumped into file: data/wiki_cn_sample/word/Vocab/pos-bioes.voc
pos-bioes	the length of it is   : 229
		Write to: data/wiki_cn_sample/word/Vocab/pos-bioes.tsv
token   	is Dumped into file: data/wiki_cn_sample/word/Vocab/token.voc
token   	the length of it is   : 2000
		Write to: data/wiki_cn_sample/word/Vocab/token.tsv
****************************************


In [2]:
BasicObject.Channel_Hyper_Path


{'token': 'data/wiki_cn_sample/word/Pyramid/_file/token.txt',
 'pos': 'data/wiki_cn_sample/word/Pyramid/_file/pos-bioes.txt'}

In [4]:
BasicObject.TOKEN

{'Sent2TokenMethod': 'pos',
 'TOKENLevel': 'word',
 'Channel_Hyper_Path': {'token': 'data/wiki_cn_sample/word/Pyramid/_file/token.txt',
  'pos': 'data/wiki_cn_sample/word/Pyramid/_file/pos-bioes.txt'},
 'length': 8407}

In [3]:
BasicObject.SENT

{'Text2SentMethod': 'whole',
 'EndIDXTokens': array([  79,  184,  291,  425,  562,  626,  686,  720,  782,  869,  977,
        1174, 1224, 1317, 1435, 1555, 1705, 1831, 1966, 2072, 2238, 2449,
        2566, 2582, 2645, 2685, 2755, 2866, 2985, 3008, 3021, 3069, 3288,
        3446, 3576, 3617, 3743, 3918, 4003, 4075, 4191, 4200, 4233, 4285,
        4322, 4357, 4402, 4422, 4436, 4472, 4538, 4629, 4699, 4791, 4868,
        5052, 5081, 5187, 5318, 5444, 5554, 5665, 5695, 5751, 5828, 5911,
        5943, 6097, 6139, 6253, 6384, 6471, 6606, 6649, 6775, 6825, 6830,
        6938, 6981, 7048, 7199, 7297, 7342, 7415, 7573, 7616, 7704, 7787,
        7797, 7828, 7905, 7923, 7958, 8011, 8085, 8137, 8191, 8238, 8365,
        8407]),
 'data/wiki_cn_sample/word/Pyramid/_file/token.txt': array([  472,  1087,  1724,  2376,  3089,  3407,  3740,  3943,  4297,
         4802,  5408,  6530,  6820,  7344,  8042,  8708,  9540, 10263,
        10994, 11608, 12532, 13711, 14359, 14454, 14794, 15020, 15426,
        

## Wiki English Sample

### Word Level

In [2]:
from nlptext.base import BasicObject

########### Wiki ###########
CORPUSPath = 'corpus/wiki_en_sample/'

Corpus2GroupMethod = '.txt'

Group2TextMethod   = 'line'

Text2SentMethod  = 'whole'

Sent2TokenMethod = 'pos_en'
TOKENLevel = 'word'
min_token_freq = 1

use_hyper = ['pos_en']

anno = False
anno_keywords = {}


BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


'File'
corpus/wiki_en_sample/wiki_en_sample.txt
Total Num of All    Tokens 47166
Total Num of Unique Tokens 8620
CORPUS	it is Dumped into file: data/wiki_en_sample/word/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
GROUP	it is Dumped into file: data/wiki_en_sample/word/Pyramid/GROUP.p
GROUP	the length of it is   : 1
TEXT	it is Dumped into file: data/wiki_en_sample/word/Pyramid/TEXT.p
TEXT	the length of it is   : 500
SENT	it is Dumped into file: data/wiki_en_sample/word/Pyramid/SENT.p
SENT	the length of it is   : 500
TOKEN	it is Dumped into file: data/wiki_en_sample/word/Pyramid/TOKEN.p
TOKEN	the length of it is   : 47166
**************************************** 

pos_en-bioes	is Dumped into file: data/wiki_en_sample/word/Vocab/pos_en-bioes.voc
pos_en-bioes	the length of it is   : 181
		Write to: data/wiki_en_sample/word/Vocab/pos_en-bioes.tsv
token   	is Dumped into file: data/wiki_en_sample/word/Vocab/token.voc
token   	the length of it is   : 8620
		Write to: data/wiki_en_sample/

# Wiki Corpus

## Wiki Chinese

### Char Level

In [1]:
from nlptext.base import BasicObject

########### Wiki ###########
CORPUSPath = 'corpus/WikiChinese/'

Corpus2GroupMethod = '.txt'

Group2TextMethod   = 'line'

Text2SentMethod  = 'whole'

Sent2TokenMethod = 'iter'
TOKENLevel = 'char'
min_token_freq = 1

use_hyper = {'pos'}

anno = False
anno_keywords = {}


BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache


'File'
corpus/WikiChinese/zhwiki_smp.txt


Loading model cost 0.637 seconds.
Prefix dict has been built succesfully.


100000 -- 109 2019-08-29 21:11:20.086077 	 14309025 	 8647 8647 8647
	 5000000 token
	 5000000 pos
200000 -- 229 2019-08-29 21:18:29.305268 	 27054049 	 10018 10018 10018
	 5000000 token
	 5000000 pos
300000 -- 89 2019-08-29 21:28:27.699765 	 39007078 	 10947 10947 10947
	 5000000 token
	 5000000 pos
400000 -- 51 2019-08-29 21:38:31.200964 	 50755371 	 11728 11728 11728
	 5000000 token
	 5000000 pos
500000 -- 180 2019-08-29 21:48:06.176919 	 62454145 	 12306 12306 12306
	 5000000 token
	 5000000 pos
600000 -- 23 2019-08-29 21:57:14.940143 	 73773949 	 12708 12708 12708
	 5000000 token
	 5000000 pos
700000 -- 66 2019-08-29 22:06:42.479607 	 84920503 	 13172 13172 13172
	 5000000 token
	 5000000 pos
800000 -- 283 2019-08-29 22:15:44.236144 	 95600635 	 13594 13594 13594
	 5000000 token
	 5000000 pos
900000 -- 224 2019-08-29 22:24:56.213239 	 105906774 	 14001 14001 14001
	 5000000 token
	 5000000 pos
1000000 -- 148 2019-08-29 22:33:18.793415 	 116116367 	 14284 14284 14284
	 5000000 toke

In [8]:
from nlptext.base import BasicObject

Data_Dir = 'data/WikiChinese/char/'
min_token_freq = 10

BasicObject.INIT_FROM_PICKLE(Data_Dir, min_token_freq)

CORPUS	read from pickle file : data/WikiChinese/char/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
GROUP	read from pickle file : data/WikiChinese/char/Pyramid/GROUP.p
GROUP	the length of it is   : 1
TEXT	read from pickle file : data/WikiChinese/char/Pyramid/TEXT.p
TEXT	the length of it is   : 4419144
SENT	read from pickle file : data/WikiChinese/char/Pyramid/SENT.p
SENT	the length of it is   : 4419144
TOKEN	read from pickle file : data/WikiChinese/char/Pyramid/TOKEN.p
TOKEN	the length of it is   : 439594499
**************************************** 



In [9]:
len(BasicObject.TokenVocab[0])

11146

In [12]:
# this is not correct
CHANNEL_SETTINGS_TEMPLATE_FOR_WIKICN = {
    # CTX_IND
    'token':   {'use': True, 'Max_Ngram': 1,},
    'pinyin':  {'use': True, 'Min_Ngram': 1, 'Max_Ngram': 4, 'end_grain': False,  'min_grain_freq' : 10},
    'subcomp': {'use': True, 'Min_Ngram': 1, 'Max_Ngram': 4, 'end_grain': False,  'min_grain_freq' : 1152},
    'stroke': { 'use': True, 'Min_Ngram': 3, 'Max_Ngram': 6, 'end_grain': False,  'min_grain_freq' : 236},
    # 'pos':     {'use': True, 'tagScheme': 'BIOES'}
}

BasicObject.BUILD_GV_LKP(CHANNEL_SETTINGS_TEMPLATE_FOR_WIKICN)

Deal with the Channel: token
Current Channel is        	 token
Current Channel Max_Ngram 	 1
Deal with the Channel: pinyin
Current Channel is        	 pinyin
Current Channel Max_Ngram 	 4
Deal with the Channel: subcomp
Current Channel is        	 subcomp
Current Channel Max_Ngram 	 4
Deal with the Channel: stroke
Current Channel is        	 stroke
Current Channel Max_Ngram 	 6
		Build Grain Uniqe and LookUp Table for channel: stroke-n3t6-f236
For channel: | stroke | build GrainUnique and LookUp
		For Channel: stroke 	 0 2019-09-04 18:02:19.095709
		Write to: data/WikiChinese/char/Vocab/F10/stroke-n3t6-f236.voc
		Write to: data/WikiChinese/char/Vocab/F10/stroke-n3t6-f236.tsv
		Write to: data/WikiChinese/char/Vocab/F10/stroke-n3t6-f236.lkp
		Write to: data/WikiChinese/char/Vocab/F10/stroke-n3t6-f236.freq


In [13]:
import pandas as pd
import numpy as np
CS = BasicObject.CHANNEL_SETTINGS
for fld in CS: 
    if fld == 'token': continue
    # fld = 'stroke'
    idx2grain = BasicObject.getGrainVocab(fld, **CS[fld])[0]

    LKP = BasicObject.getLookUp(fld, **CS[fld])[0]
    # LKP
    leng_of_char = np.array([len(i) for i in LKP])

    leng = pd.Series(leng_of_char)
    print(fld)
    print('GrainNum:', len(idx2grain))
    print(leng.describe())
    print(leng.sum())
    print(BasicObject.getFreq(fld, **CS[fld]))
    try:
        print(BasicObject.getFreq(fld, **CS[fld])[10000])
    except:
        pass
    print('======================================\n\n')

pinyin
GrainNum: 5333
count    11146.000000
mean         3.095371
std          2.109298
min          1.000000
25%          1.000000
50%          3.000000
75%          3.000000
max         10.000000
dtype: float64
34501
[64553112 45514885 33382420 ...       10       10       10]


subcomp
GrainNum: 10001
count    11146.000000
mean         5.738651
std          5.190094
min          0.000000
25%          2.000000
50%          5.000000
75%          9.000000
max         50.000000
dtype: float64
63963
[53308092 44094327 42421777 ...     1155     1155     1152]
1152


stroke
GrainNum: 10005
count    11146.000000
mean        23.517046
std         17.826554
min          0.000000
25%          6.000000
50%         22.000000
75%         37.000000
max        106.000000
dtype: float64
262121
[122034762  83201490  78056695 ...       236       236       236]
236




In [6]:
from nlptext.sentence import Sentence

sent = Sentence(100)

sent.get_grain_str('token')
sent.sentence

'就 此 , 社 会 和 历 史 的 现 象 , 便 被 赋 予 一 种 在 哲 学 史 上 还 是 崭 新 的 显 赫 地 位 。 他 还 将 伦 理 学 划 归 到 这 个 领 域 , 从 而 在 伦 理 学 理 论 和 对 思 想 的 理 解 中 提 出 重 要 的 路 线 。'

### Word Level

In [ ]:
from nlptext.base import BasicObject

########### Wiki ###########
CORPUSPath = 'corpus/WikiChinese/'

Corpus2GroupMethod = '.txt'

Group2TextMethod   = 'line'

Text2SentMethod  = 'whole'

Sent2TokenMethod = 'pos'
TOKENLevel = 'word'
min_token_freq = 1

use_hyper = ['pos']

anno = False
anno_keywords = {}


BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


In [1]:
from nlptext.base import BasicObject


##########################
min_token_freq = 10
##########################


Data_Dir = 'data/WikiChinese/word/'

BasicObject.INIT_FROM_PICKLE(Data_Dir, min_token_freq)

print(len(BasicObject.TokenVocab[0]))
print(BasicObject.idx2freq)

CORPUS	read from pickle file : data/WikiChinese/word/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
GROUP	read from pickle file : data/WikiChinese/word/Pyramid/GROUP.p
GROUP	the length of it is   : 1
TEXT	read from pickle file : data/WikiChinese/word/Pyramid/TEXT.p
TEXT	the length of it is   : 4419144
SENT	read from pickle file : data/WikiChinese/word/Pyramid/SENT.p
SENT	the length of it is   : 4419144
TOKEN	read from pickle file : data/WikiChinese/word/Pyramid/TOKEN.p
TOKEN	the length of it is   : 254754734
**************************************** 

390106
[16697636 10295030  9546380 ...       10       10       10]


In [7]:
# this is not correct
CHANNEL_SETTINGS_TEMPLATE_FOR_WIKICN = {
    # CTX_IND
    'token':   {'use': True, 'Max_Ngram': 1,},
    'char':    {'use': True, 'Min_Ngram': 1, 'Max_Ngram': 1, 'end_grain': False,  'min_grain_freq' : 15},
    'pinyin':  {'use': True, 'Min_Ngram': 1, 'Max_Ngram': 4, 'end_grain': False,  'min_grain_freq' : 15856},
    'subcomp': {'use': True, 'Min_Ngram': 1, 'Max_Ngram': 4, 'end_grain': False,  'min_grain_freq' : 21759},
    'stroke':  {'use': True, 'Min_Ngram': 3, 'Max_Ngram': 6, 'end_grain': False,  'min_grain_freq' : 19719},
}

BasicObject.BUILD_GV_LKP(CHANNEL_SETTINGS_TEMPLATE_FOR_WIKICN)

Deal with the Channel: token
Current Channel is        	 token
Current Channel Max_Ngram 	 1
Deal with the Channel: char
Current Channel is        	 char
Current Channel Max_Ngram 	 1
		Build Grain Uniqe and LookUp Table for channel: char-n1t1-f15
For channel: | char | build GrainUnique and LookUp
		For Channel: char 	 0 2019-08-26 19:50:15.093016
		For Channel: char 	 100000 2019-08-26 19:50:16.215839
		For Channel: char 	 200000 2019-08-26 19:50:17.275196
		For Channel: char 	 300000 2019-08-26 19:50:18.376059
		Write to: data/WikiChinese/word/Vocab/F10/char-n1t1-f15.voc
		Write to: data/WikiChinese/word/Vocab/F10/char-n1t1-f15.tsv
		Write to: data/WikiChinese/word/Vocab/F10/char-n1t1-f15.lkp
		Write to: data/WikiChinese/word/Vocab/F10/char-n1t1-f15.freq
Deal with the Channel: pinyin
Current Channel is        	 pinyin
Current Channel Max_Ngram 	 4
Deal with the Channel: subcomp
Current Channel is        	 subcomp
Current Channel Max_Ngram 	 4
Deal with the Channel: stroke
Current Cha

In [8]:
import pandas as pd
import numpy as np
CS = BasicObject.CHANNEL_SETTINGS
for fld in CS: 
    if fld == 'token': continue
    # fld = 'stroke'
    idx2grain = BasicObject.getGrainVocab(fld, **CS[fld])[0]

    LKP = BasicObject.getLookUp(fld, **CS[fld])[0]
    # LKP
    leng_of_char = np.array([len(i) for i in LKP])

    leng = pd.Series(leng_of_char)
    print(fld)
    print('GrainNum:', len(idx2grain))
    print(leng.describe())
    print(leng.sum())
    print(BasicObject.getFreq(fld, **CS[fld]))
    print(BasicObject.getFreq(fld, **CS[fld])[10000])
    print('======================================\n\n')

char
GrainNum: 10085
count    390106.000000
mean          2.960295
std           1.583327
min           0.000000
25%           2.000000
50%           2.000000
75%           3.000000
max          43.000000
dtype: float64
1154829
[16697636 10417042  9546380 ...       15       15       15]
15


pinyin
GrainNum: 10002
count    390106.000000
mean         12.527826
std           6.721878
min           0.000000
25%           8.000000
50%          11.000000
75%          16.000000
max         142.000000
dtype: float64
4887180
[62864529 44459023 32781276 ...    15856    15856    15856]
15856


subcomp
GrainNum: 10002
count    390106.000000
mean         14.062181
std           9.237083
min           0.000000
25%           7.000000
50%          12.000000
75%          18.000000
max         149.000000
dtype: float64
5485741
[52176468 43015399 41913615 ...    21760    21759    21759]
21759


stroke
GrainNum: 10001
count    390106.000000
mean         54.171041
std          37.389900
min           0.00

## Wiki English

### Word Level

In [ ]:
# init from origin corpus

from nlptext.base import BasicObject

########### Wiki ###########
CORPUSPath = 'corpus/WikiEnglish/'

Corpus2GroupMethod = '.txt'

Group2TextMethod   = 'line'

Text2SentMethod  = 'whole'

Sent2TokenMethod = 'pos_en'
TOKENLevel = 'word'
min_token_freq = 10

use_hyper = ['pos_en']

anno = False
anno_keywords = {}

BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


In [1]:
# init from preprocessed data
from nlptext.base import BasicObject

Data_Dir = 'data/WikiEnglish/word/'
min_token_freq = 30
BasicObject.INIT_FROM_PICKLE(Data_Dir, min_token_freq)

CORPUS	read from pickle file : data/WikiEnglish/word/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
GROUP	read from pickle file : data/WikiEnglish/word/Pyramid/GROUP.p
GROUP	the length of it is   : 1
TEXT	read from pickle file : data/WikiEnglish/word/Pyramid/TEXT.p
TEXT	the length of it is   : 37101011
SENT	read from pickle file : data/WikiEnglish/word/Pyramid/SENT.p
SENT	the length of it is   : 37101011
TOKEN	read from pickle file : data/WikiEnglish/word/Pyramid/TOKEN.p
TOKEN	the length of it is   : 2429172233
**************************************** 



In [2]:
print(len(BasicObject.TokenVocab[0]))
print(BasicObject.idx2freq)

649068
[131996922 123504303  98456073 ...        30        30        30]


In [3]:
# this is not correct
CHANNEL_SETTINGS_TEMPLATE_FOR_WIKICN = {
    # CTX_IND
    'token':   {'use': True, 'Max_Ngram': 1,},
    'char':    {'use': True, 'Min_Ngram': 1, 'Max_Ngram': 3, 'end_grain': False,  'min_grain_freq' : 2514},
    'phoneme': {'use': True, 'Min_Ngram': 1, 'Max_Ngram': 3, 'end_grain': False,  'min_grain_freq' : 1979},
}

BasicObject.BUILD_GV_LKP(CHANNEL_SETTINGS_TEMPLATE_FOR_WIKICN)

Deal with the Channel: token
Current Channel is        	 token
Current Channel Max_Ngram 	 1
Deal with the Channel: char
Current Channel is        	 char
Current Channel Max_Ngram 	 3
		Build Grain Uniqe and LookUp Table for channel: char-n1t3-f2514
For channel: | char | build GrainUnique and LookUp
		For Channel: char 	 0 2019-08-29 16:35:18.212042
		For Channel: char 	 100000 2019-08-29 16:35:20.853349
		For Channel: char 	 200000 2019-08-29 16:35:23.620032
		For Channel: char 	 300000 2019-08-29 16:35:26.439164
		For Channel: char 	 400000 2019-08-29 16:35:29.129255
		For Channel: char 	 500000 2019-08-29 16:35:32.058197
		For Channel: char 	 600000 2019-08-29 16:35:34.759977
		Write to: data/WikiEnglish/word/Vocab/F30/char-n1t3-f2514.voc
		Write to: data/WikiEnglish/word/Vocab/F30/char-n1t3-f2514.tsv
		Write to: data/WikiEnglish/word/Vocab/F30/char-n1t3-f2514.lkp
		Write to: data/WikiEnglish/word/Vocab/F30/char-n1t3-f2514.freq
Deal with the Channel: phoneme
Current Channel is      

In [5]:
import pandas as pd
import numpy as np
CS = BasicObject.CHANNEL_SETTINGS
for fld in CS: 
    if fld == 'token': continue
    # fld = 'stroke'
    idx2grain = BasicObject.getGrainVocab(fld, **CS[fld])[0]

    LKP = BasicObject.getLookUp(fld, **CS[fld])[0]
    # LKP
    leng_of_char = np.array([len(i) for i in LKP])

    leng = pd.Series(leng_of_char)
    print(fld)
    print('GrainNum:', len(idx2grain))
    print(leng.describe())
    print(leng.sum())
    print(BasicObject.getFreq(fld, **CS[fld]))
    print(BasicObject.getFreq(fld, **CS[fld])[20000])
    print('======================================\n\n')

char
GrainNum: 20003
count    649068.000000
mean         19.552623
std           9.138646
min           0.000000
25%          12.000000
50%          18.000000
75%          24.000000
max         243.000000
dtype: float64
12690982
[1163857687  829148338  801646984 ...       2514       2514       2514]
2514


phoneme
GrainNum: 20001
count    649068.00000
mean          4.10151
std           6.71414
min           1.00000
25%           1.00000
50%           1.00000
75%           1.00000
max          54.00000
dtype: float64
2662159
[773536812 609749367 509849261 ...      1980      1979      1979]
1979




In [13]:
from nlptext.sentence import Sentence

sent = Sentence(488)

sent.get_grain_str('token')
sent.sentence

"Lincoln removed McClellan in March 1862 , after McClellan offered unsolicited political advice . In July Lincoln elevated Henry Halleck . Lincoln appointed John Pope as head of the new Army of Virginia . Pope complied with Lincoln 's desire to advance on Richmond from the north , thus protecting Washington from counterattack ."

# Medical Corpora

## Luohu EMR Data (Chinese)

In [1]:
from nlptext.base import BasicObject

########### LuohuCorpus ###########
CORPUSPath = 'corpus/LuohuCorpus/'

Corpus2GroupMethod = '.p'

Group2TextMethod   = 'element'

Text2SentMethod  = 're'

Sent2TokenMethod = 'iter'
TOKENLevel = 'char'
min_token_freq = 1

use_hyper = ['pos', 'medpos']

anno = False
anno_keywords = {}

BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache


'File'
corpus/LuohuCorpus/RANinfos_PresentIllness.p


Loading model cost 0.785 seconds.
Prefix dict has been built succesfully.


corpus/LuohuCorpus/hourRecs_Treatment.p
corpus/LuohuCorpus/GetDisRecordinfos_Outoeord.p
corpus/LuohuCorpus/OperRecdatas_OperName.p
corpus/LuohuCorpus/OpEMRDatas_Tentativediagnosis.p
corpus/LuohuCorpus/hourRecs_ChiefComplaint.p
corpus/LuohuCorpus/DailyRecDatas_Text.p
100000 -- 36 2019-11-23 19:00:44.469411 	 2961104 	 2745 2745 2745
	 5000000 token
	 5000000 pos
	 5000000 medpos
200000 -- 5 2019-11-23 21:22:15.613412 	 6870587 	 3040 3040 3040
	 5000000 token
	 5000000 pos
	 5000000 medpos
300000 -- 83 2019-11-23 23:39:55.648548 	 10738060 	 3150 3150 3150
	 5000000 token
	 5000000 pos
	 5000000 medpos
corpus/LuohuCorpus/hourRecs_Outdiag.p
corpus/LuohuCorpus/GetDisRecordinfos_Ininfo.p
400000 -- 74 2019-11-24 01:48:11.791051 	 14511542 	 3250 3250 3250
	 5000000 token
	 5000000 pos
	 5000000 medpos
corpus/LuohuCorpus/GetDisRecordinfos_Indiag.p
corpus/LuohuCorpus/OpEMRDatas_AllergicHistoryFlag.p
corpus/LuohuCorpus/FirstCorinfos_Characteristics.p
500000 -- 19 2019-11-24 03:56:35.303130 	 1

In [10]:
from nlptext.base import BasicObject

Data_Dir = 'data/LuohuCorpus/char/'
min_token_freq = 1

# this is not correct
CHANNEL_SETTINGS_TEMPLATE_FOR_WIKICN = {
    # CTX_IND
    'token':   {'use': True, 'Max_Ngram': 1,},
    'pinyin':  {'use': True, 'Min_Ngram': 1, 'Max_Ngram': 1, 'end_grain': True,  'min_grain_freq' : 0},
    'subcomp': {'use': True, 'Min_Ngram': 1, 'Max_Ngram': 1, 'end_grain': True,  'min_grain_freq' : 0},
    # 'stroke': { 'use': True, 'Min_Ngram': 3, 'Max_Ngram': 6, 'end_grain': False,  'min_grain_freq' : 236},
    # 'pos':     {'use': True, 'tagScheme': 'BIOES'}
}


BasicObject.INIT_FROM_PICKLE(Data_Dir, min_token_freq)

BasicObject.BUILD_GV_LKP(CHANNEL_SETTINGS_TEMPLATE_FOR_WIKICN)

print('\n\n')

import pandas as pd
import numpy as np
CS = BasicObject.CHANNEL_SETTINGS
for fld in CS: 
    if fld == 'token': continue
    # fld = 'stroke'
    idx2grain = BasicObject.getGrainVocab(fld, **CS[fld])[0]

    LKP = BasicObject.getLookUp(fld, **CS[fld])[0]
    # LKP
    leng_of_char = np.array([len(i) for i in LKP])

    leng = pd.Series(leng_of_char)
    print(fld)
    print('GrainNum:', len(idx2grain))
    print(leng.describe())
    print(leng.sum())
    print(BasicObject.getFreq(fld, **CS[fld]))
    try:
        print(BasicObject.getFreq(fld, **CS[fld])[10000])
    except:
        pass
    print('======================================\n\n')


CORPUS	read from pickle file : data/LuohuCorpus/char/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
GROUP	read from pickle file : data/LuohuCorpus/char/Pyramid/GROUP.p
GROUP	the length of it is   : 44
TEXT	read from pickle file : data/LuohuCorpus/char/Pyramid/TEXT.p
TEXT	the length of it is   : 213908
SENT	read from pickle file : data/LuohuCorpus/char/Pyramid/SENT.p
SENT	the length of it is   : 1005357
TOKEN	read from pickle file : data/LuohuCorpus/char/Pyramid/TOKEN.p
TOKEN	the length of it is   : 36455911
**************************************** 

Deal with the Channel: token
Current Channel is        	 token
Current Channel Max_Ngram 	 1
Deal with the Channel: pinyin
Current Channel is        	 pinyin
Current Channel Max_Ngram 	 1
Deal with the Channel: subcomp
Current Channel is        	 subcomp
Current Channel Max_Ngram 	 1



pinyin
GrainNum: 306
count    3539.000000
mean        3.285391
std         0.643214
min         2.000000
25%         3.000000
50%         3.000000
75%   

In [2]:
from nlptext.sentence import Sentence

sentidx = 4000
sent = Sentence(sentidx)
sent.IdxGroup

2

In [3]:
sent.sentence

'定 期 复 查 抗 核 抗 体 谱 、 乙 肝 病 毒 定 量 、 肝 肾 功 能 等 。'

In [4]:
sent.get_grain_str('medpos')

		Build GrainUnique for channel: medpos-bio
medpos 1 False BIO
		Write to: data/LuohuCorpus/char/Vocab/medpos-bio.voc
		Write to: data/LuohuCorpus/char/Vocab/medpos-bio.tsv


[['定性-B'],
 ['定性-I'],
 ['医疗行为-B'],
 ['医疗行为-I'],
 ['治疗项目-B'],
 ['治疗项目-I'],
 ['药物-B'],
 ['药物-I'],
 ['药物-I'],
 ['连词-B'],
 ['生物-B'],
 ['生物-I'],
 ['生物-I'],
 ['生物-I'],
 ['检查项目-B'],
 ['检查项目-I'],
 ['连词-B'],
 ['身体部位-B'],
 ['身体部位-B'],
 ['身体功能-B'],
 ['身体功能-I'],
 ['虚词-B'],
 ['标点-B']]

# Sentence Classification

## Fudan Corpus

In [1]:
from nlptext.base import BasicObject

########### Wiki ###########
CORPUSPath = 'corpus/fudan/'

Corpus2GroupMethod = 'Dir'

Group2TextMethod   = 'file'

Text2SentMethod  = 'whole'

Sent2TokenMethod = ' '
TOKENLevel = 'word'
min_token_freq = 1

use_hyper = []

anno = False
anno_keywords = {}

BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


'Dir'
corpus/fudan/C39-Sports
corpus/fudan/C31-Enviornment
corpus/fudan/C38-Politics
corpus/fudan/C34-Economy
corpus/fudan/C32-Agriculture
Total Num of All    Tokens 17252831
Total Num of Unique Tokens 401556
CORPUS	it is Dumped into file: data/fudan/word/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
GROUP	it is Dumped into file: data/fudan/word/Pyramid/GROUP.p
GROUP	the length of it is   : 5
TEXT	it is Dumped into file: data/fudan/word/Pyramid/TEXT.p
TEXT	the length of it is   : 5885
SENT	it is Dumped into file: data/fudan/word/Pyramid/SENT.p
SENT	the length of it is   : 5885
TOKEN	it is Dumped into file: data/fudan/word/Pyramid/TOKEN.p
TOKEN	the length of it is   : 17252831
**************************************** 

token   	is Dumped into file: data/fudan/word/Vocab/token.voc
token   	the length of it is   : 401556
		Write to: data/fudan/word/Vocab/token.tsv
****************************************


In [4]:
from nlptext.sentence import Sentence

sentidx = 4000
sent = Sentence(sentidx)
sent.IdxGroup

3

In [5]:

from nlptext.base import BasicObject

########### Wiki ###########
CORPUSPath = 'corpus/fudan/'

Corpus2GroupMethod = 'Dir'

Group2TextMethod   = 'file'

Text2SentMethod  = 'whole'

Sent2TokenMethod = 'pos'
TOKENLevel = 'char'
min_token_freq = 1

use_hyper = ['pos']

anno = False
anno_keywords = {}

BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache


'Dir'
corpus/fudan/C39-Sports


Loading model cost 0.660 seconds.
Prefix dict has been built succesfully.


corpus/fudan/C31-Enviornment
corpus/fudan/C38-Politics
corpus/fudan/C34-Economy
corpus/fudan/C32-Agriculture
Total Num of All    Tokens 29798646
Total Num of Unique Tokens 5828
CORPUS	it is Dumped into file: data/fudan/char/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
GROUP	it is Dumped into file: data/fudan/char/Pyramid/GROUP.p
GROUP	the length of it is   : 5
TEXT	it is Dumped into file: data/fudan/char/Pyramid/TEXT.p
TEXT	the length of it is   : 5885
SENT	it is Dumped into file: data/fudan/char/Pyramid/SENT.p
SENT	the length of it is   : 5885
TOKEN	it is Dumped into file: data/fudan/char/Pyramid/TOKEN.p
TOKEN	the length of it is   : 29798646
**************************************** 

pos-bioes	is Dumped into file: data/fudan/char/Vocab/pos-bioes.voc
pos-bioes	the length of it is   : 229
		Write to: data/fudan/char/Vocab/pos-bioes.tsv
token   	is Dumped into file: data/fudan/char/Vocab/token.voc
token   	the length of it is   : 5828
		Write to: data/fudan/char/Vocab/token.tsv
***

In [4]:
from nlptext.folder import Folder
for i in range(BasicObject.GROUP['length']):
    f = Folder(i)
    print(f.name)
    s, e = f.IdxSentStartEnd
    print(e - s)


corpus/fudan/C39-Sports
1209
corpus/fudan/C31-Enviornment
1068
corpus/fudan/C38-Politics
1017
corpus/fudan/C34-Economy
1596
corpus/fudan/C32-Agriculture
995


In [6]:

from nlptext.base import BasicObject

CORPUSPath = 'corpus/newsgroup/'

Corpus2GroupMethod = 'Dir'

Group2TextMethod   = 'file'

Text2SentMethod  = 'whole'

Sent2TokenMethod = 'pos_en'
TOKENLevel = 'word'
min_token_freq = 1

use_hyper = ['pos_en']

anno = False
anno_keywords = {}

BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


'Dir'


UnboundLocalError: local variable 'group_idx' referenced before assignment

In [ ]:
from nlptext.folder import Folder
for i in range(BasicObject.GROUP['length']):
    f = Folder(i)
    print(f.name)
    s, e = f.IdxSentStartEnd
    print(e - s)


# Zhihu

In [2]:
from nlptext.base import BasicObject

########### LuohuCorpus ###########
CORPUSPath = 'corpus/ZhihuContent/'

Corpus2GroupMethod = 'Dir'

Group2TextMethod   = 'file'

Text2SentMethod  = 're'

Sent2TokenMethod = 'pos'
TOKENLevel = 'word'
min_token_freq = 10

use_hyper = ['pos']

anno = False
anno_keywords = {}

BasicObject.INIT(CORPUSPath, 
                 Corpus2GroupMethod, 
                 Group2TextMethod, 
                 Text2SentMethod, 
                 Sent2TokenMethod, TOKENLevel, min_token_freq = min_token_freq,
                 use_hyper = use_hyper, 
                 anno = False, anno_keywords = anno_keywords)


Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache


'Dir'
corpus/ZhihuContent/Live


Loading model cost 0.574 seconds.
Prefix dict has been built succesfully.


corpus/ZhihuContent/Q
100000 -- 15 2019-10-23 08:31:44.846642 	 3435530 	 108405 108405 108405
	 5000000 token
	 5000000 pos
200000 -- 11 2019-10-23 08:35:08.367620 	 6483489 	 162863 162863 162863
	 5000000 token
	 5000000 pos
300000 -- 60 2019-10-23 08:38:30.797520 	 9546254 	 203645 203645 203645
	 5000000 token
	 5000000 pos
400000 -- 7 2019-10-23 08:41:58.292255 	 12582264 	 238372 238372 238372
	 5000000 token
	 5000000 pos
500000 -- 87 2019-10-23 08:45:23.404024 	 15657132 	 268726 268726 268726
	 5000000 token
	 5000000 pos
corpus/ZhihuContent/Art
600000 -- 19 2019-10-23 08:48:29.650688 	 18689797 	 306634 306634 306634
	 5000000 token
	 5000000 pos
700000 -- 32 2019-10-23 08:51:31.108083 	 21719950 	 351829 351829 351829
	 5000000 token
	 5000000 pos
800000 -- 16 2019-10-23 08:54:21.888990 	 24818501 	 392164 392164 392164
	 5000000 token
	 5000000 pos
900000 -- 29 2019-10-23 08:57:15.080027 	 27818621 	 430861 430861 430861
	 5000000 token
	 5000000 pos
1000000 -- 116 2019-10

7600000 -- 26 2019-10-23 12:17:51.621794 	 231782873 	 1902302 1902302 1902302
	 9000000 token
	 9000000 pos
7700000 -- 24 2019-10-23 12:21:05.380103 	 234792236 	 1914690 1914690 1914690
	 9000000 token
	 9000000 pos
7800000 -- 27 2019-10-23 12:24:30.721221 	 237789639 	 1926914 1926914 1926914
	 9000000 token
	 9000000 pos
7900000 -- 92 2019-10-23 12:27:44.138750 	 240802100 	 1939614 1939614 1939614
	 9000000 token
	 9000000 pos
8000000 -- 52 2019-10-23 12:31:00.178213 	 243823847 	 1952343 1952343 1952343
	 9000000 token
	 9000000 pos
8100000 -- 12 2019-10-23 12:34:11.746327 	 246758587 	 1963749 1963749 1963749
	 9000000 token
	 9000000 pos
8200000 -- 27 2019-10-23 12:37:28.719000 	 249797933 	 1975942 1975942 1975942
	 9000000 token
	 9000000 pos
8300000 -- 32 2019-10-23 12:40:48.117807 	 252825976 	 1988344 1988344 1988344
	 9000000 token
	 9000000 pos
8400000 -- 30 2019-10-23 12:43:59.413263 	 255802458 	 2000659 2000659 2000659
	 9000000 token
	 9000000 pos
8500000 -- 14 2019-

14800000 -- 8 2019-10-23 16:16:00.512404 	 447990623 	 2698524 2698524 2698524
	 15000000 token
	 15000000 pos
14900000 -- 18 2019-10-23 16:19:15.708498 	 450994073 	 2707764 2707764 2707764
	 15000000 token
	 15000000 pos
	Enlarging the SENT size...
	current leng is: 15000000
	updated leng is: 17000000
15000000 -- 11 2019-10-23 16:22:42.726538 	 454008067 	 2718028 2718028 2718028
	 17000000 token
	 17000000 pos
15100000 -- 12 2019-10-23 16:25:52.996854 	 456995939 	 2727484 2727484 2727484
	 17000000 token
	 17000000 pos
15200000 -- 30 2019-10-23 16:29:16.740313 	 460028820 	 2738632 2738632 2738632
	 17000000 token
	 17000000 pos
15300000 -- 27 2019-10-23 16:32:44.199056 	 463100478 	 2748403 2748403 2748403
	 17000000 token
	 17000000 pos
15400000 -- 14 2019-10-23 16:36:13.947963 	 466132815 	 2759064 2759064 2759064
	 17000000 token
	 17000000 pos
15500000 -- 24 2019-10-23 16:39:43.683425 	 469102353 	 2769137 2769137 2769137
	 17000000 token
	 17000000 pos
15600000 -- 43 2019-10-

In [4]:
from nlptext.text import Text


t = Text(500030)
t

<txt Ans569325274.txt 500030>

In [5]:
doc = [i.sentence for i in t.Sentences]
doc

['初 中 同 桌 是 女 生 , 我 俩 都 是 全 班 前 三 名 , 我 天 天 跟 人 家 暗 中 较 着 劲 。',
 '这 天 体 检 , 大 家 都 拿 着 自 己 的 表 排 队 体 检 。',
 '回 来 后 我 一 把 把 她 的 体 检 表 抢 过 来 , 看 看 有 没 有 超 过 我 的 地 方 。',
 '然 后 我 发 现 了 新 大 陆 , 顿 时 火 冒 三 丈 , 用 足 以 让 半 个 班 同 学 都 能 听 清 的 音 量 对 她 大 吼 一 声 : X X X ( 同 桌 名 字 ) ! 你 怎 么 能 胸 围 比 我 还 大 ! … …',
 '同 学 们 : h h h h h h h h h h h h h h … …',
 '我 : ? ? ? ? ? 班 主 任 也 在 场 。',
 '她 很 亲 切 地 叫 我 “ 来 办 公 室 ” 。',
 '我 在 众 人 的 哄 笑 声 中 , 懵 逼 地 跟 在 老 师 后 面 进 了 办 公 室 , 她 让 我 坐 下 来 , 很 和 蔼 地 和 我 简 短 讲 了 一 些 生 理 卫 生 知 识 。',
 '后 来 当 然 是 懂 了 , 不 过 被 嘲 笑 了 好 长 好 长 好 长 时 间 … …',
 '至 少 毕 业 十 五 年 聚 会 的 时 候 , 还 t m 有 人 记 得 … …',
 '我 确 实 是 比 较 后 知 后 觉 吧 , 都 初 中 了 , 什 么 都 不 明 白 。',
 '我 上 的 是 五 年 制 小 学 , 又 提 前 一 年 入 学 。',
 '那 一 年 , 我 应 该 是 1 1 岁 。',
 '三 百 赞 了 啊 … …',
 '一 千 赞 , 承 蒙 厚 爱 , 感 激 不 尽 … …']

In [6]:
sents = t.Sentences
sents

[<st 9933486 (tokenNum: 30) >,
 <st 9933487 (tokenNum: 19) >,
 <st 9933488 (tokenNum: 28) >,
 <st 9933489 (tokenNum: 63) >,
 <st 9933490 (tokenNum: 20) >,
 <st 9933491 (tokenNum: 14) >,
 <st 9933492 (tokenNum: 14) >,
 <st 9933493 (tokenNum: 51) >,
 <st 9933494 (tokenNum: 24) >,
 <st 9933495 (tokenNum: 22) >,
 <st 9933496 (tokenNum: 24) >,
 <st 9933497 (tokenNum: 18) >,
 <st 9933498 (tokenNum: 12) >,
 <st 9933499 (tokenNum: 7) >,
 <st 9933500 (tokenNum: 15) >]

In [7]:
def extractSET(tag_seq, exist_SE = False):
    '''
        SET: start, end, tag
        tag_seq: the hyper field sequence for this sentence
    '''
    if exist_SE:
        tag_seq = tag_seq[1:-1]

    IT = list(zip(range(len(tag_seq)), tag_seq))
    taggedIT = [it for it in IT if it[1]!= 'O']
    
    startIdx = [idx for idx in range(len(taggedIT)) if taggedIT[idx][1][-2:] == '-B' or taggedIT[idx][1][-2:] == '-S']
    startIdx.append(len(taggedIT))

    entitiesList = []
    for i in range(len(startIdx)-1):
        entityAtom = taggedIT[startIdx[i]: startIdx[i+1]]
        # string = ''.join([cit[0] for cit in entityAtom])
        start, end = entityAtom[0][0], entityAtom[-1][0] + 1
        tag = entityAtom[0][1].split('-')[0]
        entitiesList.append((start, end, tag))
    return entitiesList



In [8]:
def clean_text(t, selected_pos_list = None):
    sents = t.Sentences
    for sent in sents: # sent = sents[12]
        pos = [i[0] for i in sent.get_grain_str('pos')]
        tokens = [i[0] for i in sent.get_grain_str('token')]

        L = []
        SET = extractSET(pos)
        for s_e_t in SET:
            s, e, t = s_e_t
            # if t in selected_pos_list:
            if True:
                orig = ''.join(tokens[s:e])
                L.append((orig, t))

    return L

In [9]:
text = Text(100)
clean_text(text)

[('该', 'r'),
 ('如何', 'r'),
 ('理解', 'v'),
 ('双', 'n'),
 ('离合', 'v'),
 ('变速器', 'n'),
 ('市面上', 'n'),
 ('越来越', 'd'),
 ('多', 'm'),
 ('的', 'uj'),
 ('车', 'n'),
 ('开始', 'v'),
 ('搭载', 'v'),
 ('双', 'n'),
 ('离合', 'v'),
 ('变速器', 'n'),
 (',', 'x'),
 ('但是', 'c'),
 ('大家', 'n'),
 ('都', 'd'),
 ('还', 'd'),
 ('对', 'p'),
 ('这', 'r'),
 ('一新', 'd'),
 ('技术', 'n'),
 ('有所', 'n'),
 ('迟疑', 'd'),
 (',', 'x'),
 ('我', 'r'),
 ('将', 'd'),
 ('在', 'p'),
 ('这场', 'mq'),
 ('live', 'eng'),
 ('中', 'f'),
 ('从', 'p'),
 ('双', 'n'),
 ('离合', 'v'),
 ('变速器', 'n'),
 ('的', 'uj'),
 ('运行', 'v'),
 ('原理', 'n'),
 ('到', 'v'),
 ('制造', 'v'),
 ('工艺', 'n'),
 ('为', 'p'),
 ('大家', 'n'),
 ('答疑', 'v'),
 ('解惑', 'v'),
 ('!', 'x'),
 ('•', 'x'),
 ('什么', 'r'),
 ('是', 'v'),
 ('变速器', 'n'),
 ('•', 'x'),
 ('双', 'n'),
 ('离合', 'v'),
 ('变速器', 'n'),
 ('的', 'uj'),
 ('历史', 'n'),
 ('•', 'x'),
 ('什么', 'r'),
 ('是', 'v'),
 ('双', 'n'),
 ('离合', 'v'),
 ('变速器', 'n'),
 ('•', 'x'),
 ('双', 'n'),
 ('离合', 'v'),
 ('变速器', 'n'),
 ('的', 'uj'),
 ('优势', 'n'),
 ('•', 'x'),
 ('国内', 

In [10]:
text = Text(1002)
clean_text(text)

[('引子', 'n'),
 (':', 'x'),
 ('关于', 'p'),
 ('本次', 'r'),
 ('Live', 'eng'),
 ('的', 'uj'),
 ('适用人群', 'n'),
 ('和', 'c'),
 ('一点', 'm'),
 ('个人', 'n'),
 ('看法', 'v'),
 ('-', 'x'),
 ('个人', 'n'),
 ('意见', 'n'),
 (',', 'x'),
 ('仅供参考', 'l'),
 ('第一篇', 'm'),
 (':', 'x'),
 ('教育', 'vn'),
 ('是', 'v'),
 ('为了', 'p'),
 ('什么', 'r'),
 ('?', 'x'),
 ('-', 'x'),
 ('教育', 'vn'),
 ('的', 'uj'),
 ('最终', 'd'),
 ('目的', 'n'),
 ('-', 'x'),
 ('高效', 'a'),
 ('的', 'uj'),
 ('课堂', 'n'),
 ('学习', 'v'),
 ('-', 'x'),
 ('教育', 'vn'),
 ('活动', 'vn'),
 ('与', 'p'),
 ('学生', 'n'),
 ('响应', 'v'),
 ('-', 'x'),
 ('教师', 'n'),
 ('的', 'uj'),
 ('角色', 'n'),
 ('转化', 'v'),
 ('与', 'p'),
 ('衔接', 'v'),
 ('-', 'x'),
 ('本章', 'r'),
 ('总结', 'n'),
 ('第二篇', 'm'),
 (':', 'x'),
 ('教育', 'vn'),
 ('活动', 'vn'),
 ('的', 'uj'),
 ('策划', 'n'),
 ('与', 'p'),
 ('开展', 'v'),
 ('-', 'x'),
 ('什么', 'r'),
 ('是', 'v'),
 ('教育', 'vn'),
 ('活动', 'vn'),
 ('-', 'x'),
 ('教育', 'vn'),
 ('活动', 'vn'),
 ('的', 'uj'),
 ('最终目标', 'l'),
 ('-', 'x'),
 ('教育', 'vn'),
 ('与', 'p'),
 ('德育', 'nr'),
 ('

In [54]:
import pandas as pd

stopwords = [i[0] for i in pd.read_csv('nlptext/sources/stopwords/中文停用词表.txt', header = None).values]
len(stopwords)

746

In [50]:

len(stopwords)

1395

In [51]:
stopwords

['--',
 '?',
 '“',
 '”',
 '》',
 '－－',
 'able',
 'about',
 'above',
 'according',
 'accordingly',
 'across',
 'actually',
 'after',
 'afterwards',
 'again',
 'against',
 "ain't",
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'an',
 'and',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'apart',
 'appear',
 'appreciate',
 'appropriate',
 'are',
 "aren't",
 'around',
 'as',
 "a's",
 'aside',
 'ask',
 'asking',
 'associated',
 'at',
 'available',
 'away',
 'awfully',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'believe',
 'below',
 'beside',
 'besides',
 'best',
 'better',
 'between',
 'beyond',
 'both',
 'brief',
 'but',
 'by',
 'came',
 'can',
 'cannot',
 'cant',
 "can't",
 'cause',
 'causes',
 'certain',
 'certainly',
 'changes',
 'clearly',
 "c'mon",
 'co',
 'com',
